# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wet < Formula
  desc "Context compression proxy for Claude Code"
  homepage "https://github.com/buildoak/wet"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/buildoak/wet/releases/download/v0.1.4/wet_0.1.4_darwin_amd64.tar.gz"
      sha256 "6b2c913881df5ce44c321844fcfe70a445dc1d282b26bb2aad7f010771535efd"

      define_method(:install) do
        bin.install "wet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/buildoak/wet/releases/download/v0.1.4/wet_0.1.4_darwin_arm64.tar.gz"
      sha256 "a31c95f22fb318870c8445e8de6847c963d69a75e9376be86cbf8eae4b234800"

      define_method(:install) do
        bin.install "wet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/buildoak/wet/releases/download/v0.1.4/wet_0.1.4_linux_amd64.tar.gz"
      sha256 "909bfe2469badcfdf12df76330a8c571a4b3484f8dffd44528241a784a2e52da"
      define_method(:install) do
        bin.install "wet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/buildoak/wet/releases/download/v0.1.4/wet_0.1.4_linux_arm64.tar.gz"
      sha256 "bd2e5c1e93befa1c88017c0d41cb78d926f78338da27369bb5e43576574f2f6e"
      define_method(:install) do
        bin.install "wet"
      end
    end
  end
end
