# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wet < Formula
  desc "Context compression proxy for Claude Code"
  homepage "https://github.com/buildoak/wet"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/buildoak/wet/releases/download/v0.1.5/wet_0.1.5_darwin_amd64.tar.gz"
      sha256 "5a7b0bf89c2edbd7869789f371454bd2bd516887fcfae60aa47de81400259e6b"

      define_method(:install) do
        bin.install "wet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/buildoak/wet/releases/download/v0.1.5/wet_0.1.5_darwin_arm64.tar.gz"
      sha256 "15cc8606e96517a090ef1f13cb7a453127c66bc2c0715fdb1c607af669522915"

      define_method(:install) do
        bin.install "wet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/buildoak/wet/releases/download/v0.1.5/wet_0.1.5_linux_amd64.tar.gz"
      sha256 "bd71fe46b5aac303f5aec6bbb97060cc8af28b9d5a549483f3ac5870c5171720"
      define_method(:install) do
        bin.install "wet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/buildoak/wet/releases/download/v0.1.5/wet_0.1.5_linux_arm64.tar.gz"
      sha256 "ca5500468d1746de96d12c12f63939381636c7b7ac3ddd1174924b1955ea4a0f"
      define_method(:install) do
        bin.install "wet"
      end
    end
  end
end
